version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8080:8080
        # depends_on:
        #     - localhost
        #     - phpmyadmin         

    # database:
    #     container_name: database
    #     image: mysql:8.0
    #     ports:
    #         -   3306:3306
    #     environment:
    #         - MYSQL_DATABASE=laravel
    #         - MYSQL_USER=secret
    #         - MYSQL_PASSWORD=secret
    #         - MYSQL_ROOT_PASSWORD=secret
    #     volumes:
    #         - db-data:/var/lib/mysql   

    # localhost:
    #   image: mysql:latest
    #   environment:
    #     MYSQL_ROOT_PASSWORD: secret
    #     MYSQL_DATABASE: laravel_docker
    #   ports:
    #   - 3306:3306
    
    # phpmyadmin:
    #   image: phpmyadmin:latest
    #   ports:
    #     - 9001:80
    #   environment:
    #     - PMA_ARBITRARY=1

# volumes:
#     db-data: ~